service: serverless-chatbot

provider:
  name: aws
  runtime: nodejs12.x

  iamManagedPolicies:
    - "arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"

  environment:
    BEEKEEPER_TENANT_URL: ${file(./config.yml):tenantUrl}
    BEEKEEPER_API_TOKEN: ${file(./config.yml):apiToken}

functions:
  messageReceived:
    handler: src/handler.handleMessageReceived
    events:
      - http:
          path: message-received
          method: post
