version: "2"
services:
  app:
    build: .
    volumes:
      - ./package.json:/opt/former/package.json
      - ./former:/opt/former/former
    ports:
      - "5003:5003"
    environment:
      AWS_ACCESS_KEY_ID: <YOUR ACCESS KEY>
      AWS_SECRET_ACCESS_KEY: <YOUR SECRET KEY>
      AWS_REGION: <YOUR AWS SES REGION>
      BEEKEEPER_JWT_PUBLIC_KEY: |-
        <BEEKEEPER SIGNING KEY>
